version: '3.3'

services:
  web:
    restart: on-failure
    build:
      context: .
      args:
        APP_ENV: ${APP_ENV}
    container_name: cmr_service
    volumes:
      - .:/django-docker
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    depends_on:
      - postgres
    environment:
      APP_ENV: ${APP_ENV:-dev}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_DATABASE: ${POSTGRES_DATABASE_CMR}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_PORT: ${DJANGO_PORT}
      DJANGO_SU_NAME: ${DJANGO_SU_NAME}
      DJANGO_SU_EMAIL: ${DJANGO_SU_EMAIL}
      DJANGO_SU_PASSWORD: ${DJANGO_SU_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}

  postgres:
      restart: always
      image: postgres:latest
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DATABASE_CMR}
      ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
